#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - echo Installing microk8s
  - snap install microk8s --channel=1.19/edge --classic
  - echo Enabling addons
  - microk8s enable ingress dns storage rbac dashboard
  - echo Adding user ubuntu to microk8s group
  - usermod -a -G microk8s ubuntu
  - mkdir -p /home/ubuntu/.kube
  - chown -f -R ubuntu /home/ubuntu/.kube
