#cloud-config
package_update: true
package_upgrade: true

users:
  - name: nuttingd
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id: gh:nuttingd
    shell: /usr/bin/bash

runcmd:
  - echo Installing microk8s
  - snap install microk8s --channel=1.19/edge --classic
  - echo Enabling addons
  - microk8s enable dns storage rbac dashboard
  - echo Adding user ubuntu to microk8s group
  - usermod -a -G microk8s ubuntu
  - chown -f -R ubuntu /home/ubuntu/.kube
  - echo Adding user nuttingd to microk8s group
  - usermod -a -G microk8s nuttingd
  - chown -f -R nuttingd /home/nuttingd/.kube
